### ISSUE TITLE
feature-request: Numerically sort keys

### ISSUE THREAD

**Issue by ryanmjacobs** [monterail/redis-browser#14]
Currently, keys are sorted "alphanumerically". It would be nice to have keys that are purely numeric sorted by value instead.

![currently unsorted keys](https://cloud.githubusercontent.com/assets/4251257/5563155/dfa342d8-8e10-11e4-9439-1aefb93e0a38.png)

**Comment by teamon** [comment]
Hi @ryanmjacobs, are you still interested in this feature? If yes, do you have any smart way to implement such sorting?

**Comment by ryanmjacobs** [comment]
Hey @teamon, sorry for not following up sooner. I'm not really using redis-browser anymore, so I don't have a use for this feature. Feel free to close this issue if you want.
