### ISSUE TITLE
Not rendering template on production

### ISSUE THREAD

**Issue by kenn** [monterail/redis-browser#16]
Not sure where I'm doing it wrong, but `/redis-browser/js/angular.min.js` fails to load and `angular` triggers ReferenceError on and only on production.

Thoughts?

![screen shot 2015-05-29 at 9 10 40 pm](https://cloud.githubusercontent.com/assets/10350/7882325/62132f68-0647-11e5-8223-c520d4df5f1b.png)

**Comment by teamon** [comment]
What's inside Network tab? Are there any 404's ?

**Comment by kenn** [comment]
It's no longer reproducible. Maybe that was a config issue?
