### ISSUE TITLE
undefined method `this' for #<Gem::Specification:0x507ef22 rack-1.6.4> (NoMethodError)

### ISSUE THREAD

**Issue by mulaiko** [monterail/redis-browser#25]
Hi,

I receive the following error when I run redis-browser

`.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2159:in `method_missing': undefined method `this' for #<Gem::Specification:0x507ef22 rack-1.6.4> (NoMethodError)`

Please advise as to how I would resolve this issue.

**Comment by szajbus** [comment]
@mulaiko This is a rubygems bug. I believe you should update rubygems and try again.

More info here https://github.com/rubygems/rubygems/issues/1420
